"""add calendar.user_id

Revision ID: 2d197e503953
Revises: a53afb02f223
Create Date: 2023-11-07 20:10:45.833894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d197e503953'
down_revision: Union[str, None] = 'a53afb02f223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('user_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar', 'user_id')
    # ### end Alembic commands ###
