"""add auth_session.token

Revision ID: f97346d363d4
Revises: 2d197e503953
Create Date: 2023-11-09 17:20:49.057092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f97346d363d4'
down_revision: Union[str, None] = '2d197e503953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_session', sa.Column('token', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_session', 'token')
    # ### end Alembic commands ###
